import type { Question } from '@/types';

/**
 * Real chemistry content a Nigerian SS2 / SS3 teacher would actually set:
 * organic chemistry, mole concept, acids and bases, electrolysis, periodic
 * table, qualitative reactions. Mix of MCQ, short answer, long answer, and
 * handwritten.
 *
 * Question 0xx — SS3 Mid-Term (live)
 * Question 1xx — SS2 Quiz Week 4 (grading)
 * Question 2xx — SS3 First Term Exam (ready to publish)
 * Question 3xx — SS1 Test 1 (published)
 * Question 9xx — Bank only
 */
export const questions: Question[] = [
  // ────────────────────────────────────────────────────────────────
  // SS3 Chemistry Mid-Term (live)
  // ────────────────────────────────────────────────────────────────
  {
    id: 'q_001',
    exam_id: 'exm_ss3_midterm',
    type: 'mcq',
    content: 'Which of the following is an alkane?',
    marks: 2,
    expected_answer: 'C2H6',
    mcq_options: [
      { id: 'a', text: 'C2H4', is_correct: false },
      { id: 'b', text: 'C2H6', is_correct: true },
      { id: 'c', text: 'C2H2', is_correct: false },
      { id: 'd', text: 'C3H6', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_002',
    exam_id: 'exm_ss3_midterm',
    type: 'mcq',
    content: 'The IUPAC name for CH3CH2CH(OH)CH3 is',
    marks: 2,
    expected_answer: 'butan-2-ol',
    mcq_options: [
      { id: 'a', text: 'butan-1-ol', is_correct: false },
      { id: 'b', text: 'butan-2-ol', is_correct: true },
      { id: 'c', text: '2-methylpropan-1-ol', is_correct: false },
      { id: 'd', text: 'butanal', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_003',
    exam_id: 'exm_ss3_midterm',
    type: 'short_answer',
    content:
      'Define isomerism. Give one example of structural isomerism in alkanes.',
    marks: 4,
    expected_answer:
      'Isomerism is the existence of two or more compounds with the same molecular formula but different structural arrangements. Example: butane (CH3CH2CH2CH3) and 2-methylpropane (isobutane) both have molecular formula C4H10.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_004',
    exam_id: 'exm_ss3_midterm',
    type: 'mcq',
    content: 'Which functional group is present in ethanoic acid?',
    marks: 2,
    expected_answer: '—COOH (carboxyl)',
    mcq_options: [
      { id: 'a', text: '—OH (hydroxyl)', is_correct: false },
      { id: 'b', text: '—CHO (aldehyde)', is_correct: false },
      { id: 'c', text: '—COOH (carboxyl)', is_correct: true },
      { id: 'd', text: '—CO— (carbonyl)', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_005',
    exam_id: 'exm_ss3_midterm',
    type: 'long_answer',
    content:
      'Describe the laboratory preparation of ethyne (acetylene) from calcium carbide. Include the balanced equation and explain how the gas should be collected, giving a reason for the method.',
    marks: 8,
    expected_answer:
      'Calcium carbide (CaC2) is added to water in a flask fitted with a delivery tube. The reaction releases ethyne gas: CaC2 + 2H2O → Ca(OH)2 + C2H2. The gas is collected over water by downward displacement of water because ethyne is only slightly soluble in water and is lighter than air.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_006',
    exam_id: 'exm_ss3_midterm',
    type: 'mcq',
    content: 'The product formed when ethene reacts with bromine water is',
    marks: 2,
    expected_answer: '1,2-dibromoethane',
    mcq_options: [
      { id: 'a', text: 'bromoethane', is_correct: false },
      { id: 'b', text: '1,1-dibromoethane', is_correct: false },
      { id: 'c', text: '1,2-dibromoethane', is_correct: true },
      { id: 'd', text: 'ethanol', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_007',
    exam_id: 'exm_ss3_midterm',
    type: 'short_answer',
    content:
      'State two differences between addition and substitution reactions. Give one example of each.',
    marks: 4,
    expected_answer:
      'Addition reactions occur in unsaturated compounds (alkenes, alkynes) where a small molecule adds across a multiple bond, e.g. ethene + Br2 → 1,2-dibromoethane. Substitution reactions occur in saturated compounds (alkanes) where one atom or group replaces another, e.g. CH4 + Cl2 → CH3Cl + HCl (in sunlight).',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_008',
    exam_id: 'exm_ss3_midterm',
    type: 'handwritten',
    content:
      'Draw the structure of 2-methylbut-2-ene. Show all bonds clearly and label the position of the double bond.',
    marks: 4,
    expected_answer:
      'Structure: (CH3)2C=CHCH3. Carbon-2 and carbon-3 are joined by a double bond, with a methyl group on carbon-2.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_009',
    exam_id: 'exm_ss3_midterm',
    type: 'mcq',
    content: 'Which of these compounds is a primary alcohol?',
    marks: 2,
    expected_answer: 'propan-1-ol',
    mcq_options: [
      { id: 'a', text: 'propan-2-ol', is_correct: false },
      { id: 'b', text: 'propan-1-ol', is_correct: true },
      { id: 'c', text: '2-methylpropan-2-ol', is_correct: false },
      { id: 'd', text: 'butan-2-ol', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_010',
    exam_id: 'exm_ss3_midterm',
    type: 'long_answer',
    content:
      'Ethanol is sometimes added to petrol to produce gasohol. State two advantages and one disadvantage of this practice, giving reasons.',
    marks: 6,
    expected_answer:
      'Advantages: (1) Ethanol is a renewable fuel produced from fermentation of sugar/starch crops, reducing reliance on crude oil. (2) Ethanol burns more cleanly than petrol, producing fewer particulates and lower CO emissions. Disadvantage: Ethanol absorbs water, which can cause corrosion in fuel systems and engine starting problems in older vehicles.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },

  // ────────────────────────────────────────────────────────────────
  // SS2 Chemistry Quiz Week 4 (grading)
  // ────────────────────────────────────────────────────────────────
  {
    id: 'q_101',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'mcq',
    content: 'The pH of pure water at 25°C is',
    marks: 1,
    expected_answer: '7',
    mcq_options: [
      { id: 'a', text: '0', is_correct: false },
      { id: 'b', text: '7', is_correct: true },
      { id: 'c', text: '14', is_correct: false },
      { id: 'd', text: '1', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_102',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'mcq',
    content: 'Which of the following is a strong base?',
    marks: 1,
    expected_answer: 'NaOH',
    mcq_options: [
      { id: 'a', text: 'NH3', is_correct: false },
      { id: 'b', text: 'NaOH', is_correct: true },
      { id: 'c', text: 'CH3COOH', is_correct: false },
      { id: 'd', text: 'Cu(OH)2', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_103',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'short_answer',
    content:
      'Calculate the number of moles in 4.9 g of H2SO4. (H = 1, S = 32, O = 16)',
    marks: 3,
    expected_answer:
      'Molar mass of H2SO4 = 2(1) + 32 + 4(16) = 98 g/mol. Moles = 4.9 / 98 = 0.05 mol.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_104',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'mcq',
    content: 'The conjugate base of HCl is',
    marks: 1,
    expected_answer: 'Cl⁻',
    mcq_options: [
      { id: 'a', text: 'H⁺', is_correct: false },
      { id: 'b', text: 'OH⁻', is_correct: false },
      { id: 'c', text: 'Cl⁻', is_correct: true },
      { id: 'd', text: 'H3O⁺', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_105',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'short_answer',
    content: "State Avogadro's law.",
    marks: 2,
    expected_answer:
      'Equal volumes of all gases, measured at the same temperature and pressure, contain the same number of molecules.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_106',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'handwritten',
    content:
      'Balance the following equation, showing your working clearly:\n___ HCl + ___ Ca(OH)2 → ___ CaCl2 + ___ H2O',
    marks: 3,
    expected_answer: '2HCl + Ca(OH)2 → CaCl2 + 2H2O',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_107',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'mcq',
    content:
      'When a few drops of universal indicator are added to a solution of pH 11, the colour observed is',
    marks: 1,
    expected_answer: 'blue',
    mcq_options: [
      { id: 'a', text: 'red', is_correct: false },
      { id: 'b', text: 'yellow', is_correct: false },
      { id: 'c', text: 'green', is_correct: false },
      { id: 'd', text: 'blue', is_correct: true },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_108',
    exam_id: 'exm_ss2_quiz_w4',
    type: 'short_answer',
    content:
      'Define molarity. A solution contains 0.5 mol of NaOH dissolved in 250 cm³ of water. Calculate its molarity.',
    marks: 4,
    expected_answer:
      'Molarity is the number of moles of solute dissolved per cubic decimetre (litre) of solution. Molarity = 0.5 / (250/1000) = 0.5 / 0.25 = 2 mol/dm³.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },

  // ────────────────────────────────────────────────────────────────
  // SS3 First Term Exam (ready to publish)
  // ────────────────────────────────────────────────────────────────
  {
    id: 'q_201',
    exam_id: 'exm_ss3_first_term',
    type: 'mcq',
    content: 'In the contact process for the manufacture of sulphuric acid, the catalyst used is',
    marks: 2,
    expected_answer: 'V2O5',
    mcq_options: [
      { id: 'a', text: 'Fe', is_correct: false },
      { id: 'b', text: 'Pt', is_correct: false },
      { id: 'c', text: 'V2O5', is_correct: true },
      { id: 'd', text: 'MnO2', is_correct: false },
    ],
    has_image: true,
    image_url: '/mock-images/contact-process.png',
    question_bank_id: 'qb_waec_chem',
    saved_to_bank: true,
  },
  {
    id: 'q_202',
    exam_id: 'exm_ss3_first_term',
    type: 'mcq',
    content:
      'During the electrolysis of dilute H2SO4 using inert electrodes, the gas liberated at the cathode is',
    marks: 2,
    expected_answer: 'hydrogen',
    mcq_options: [
      { id: 'a', text: 'oxygen', is_correct: false },
      { id: 'b', text: 'hydrogen', is_correct: true },
      { id: 'c', text: 'sulphur dioxide', is_correct: false },
      { id: 'd', text: 'chlorine', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_waec_chem',
    saved_to_bank: true,
  },
  {
    id: 'q_203',
    exam_id: 'exm_ss3_first_term',
    type: 'short_answer',
    content:
      'Explain why aluminium is extracted by electrolysis rather than reduction with carbon.',
    marks: 4,
    expected_answer:
      'Aluminium is more reactive than carbon, so carbon cannot reduce aluminium oxide to aluminium. Aluminium also forms a very stable oxide (Al2O3) with strong ionic bonds. Electrolysis of molten Al2O3 (dissolved in cryolite to lower the melting point) is therefore used to obtain pure aluminium.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_204',
    exam_id: 'exm_ss3_first_term',
    type: 'long_answer',
    content:
      'Describe two methods of preventing the rusting of iron, explaining how each method works.',
    marks: 6,
    expected_answer:
      'Method 1 — Galvanising: coating iron with a layer of zinc. Zinc is more reactive than iron and oxidises preferentially (sacrificial protection), preventing iron from rusting even if the coating is scratched. Method 2 — Painting: applying a layer of paint or oil. This forms a barrier that prevents air and moisture from reaching the iron surface, so the conditions for rusting are not present.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_205',
    exam_id: 'exm_ss3_first_term',
    type: 'mcq',
    content: 'The hybridization of the carbon atoms in ethyne (HC≡CH) is',
    marks: 2,
    expected_answer: 'sp',
    mcq_options: [
      { id: 'a', text: 'sp', is_correct: true },
      { id: 'b', text: 'sp²', is_correct: false },
      { id: 'c', text: 'sp³', is_correct: false },
      { id: 'd', text: 'sp³d', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },
  {
    id: 'q_206',
    exam_id: 'exm_ss3_first_term',
    type: 'short_answer',
    content:
      'Write the balanced equation for the reaction between sodium and water, and state two observations made during the reaction.',
    marks: 4,
    expected_answer:
      '2Na + 2H2O → 2NaOH + H2. Observations: (1) Sodium melts into a silvery ball that floats on the water and moves around the surface. (2) A hissing sound is produced and the gas evolved (hydrogen) sometimes ignites with a yellow flame.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_waec_chem',
    saved_to_bank: true,
  },
  {
    id: 'q_207',
    exam_id: 'exm_ss3_first_term',
    type: 'handwritten',
    content:
      'Draw a labelled diagram of the apparatus used to collect a gas that is denser than air and very soluble in water.',
    marks: 5,
    expected_answer:
      'Diagram should show a gas-generating flask connected via a delivery tube to a gas jar held upright (mouth up). The gas is collected by upward delivery (downward displacement of air). Labels: round-bottom flask, delivery tube, gas jar, lid/cover.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_208',
    exam_id: 'exm_ss3_first_term',
    type: 'mcq',
    content: 'The functional group —CHO is found in',
    marks: 2,
    expected_answer: 'aldehydes',
    mcq_options: [
      { id: 'a', text: 'alcohols', is_correct: false },
      { id: 'b', text: 'aldehydes', is_correct: true },
      { id: 'c', text: 'ketones', is_correct: false },
      { id: 'd', text: 'carboxylic acids', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_organic_ss3',
    saved_to_bank: true,
  },

  // ────────────────────────────────────────────────────────────────
  // SS1 Test 1 (published)
  // ────────────────────────────────────────────────────────────────
  {
    id: 'q_301',
    exam_id: 'exm_ss1_test1',
    type: 'mcq',
    content: 'The element with atomic number 11 is',
    marks: 1,
    expected_answer: 'Sodium (Na)',
    mcq_options: [
      { id: 'a', text: 'Lithium (Li)', is_correct: false },
      { id: 'b', text: 'Sodium (Na)', is_correct: true },
      { id: 'c', text: 'Potassium (K)', is_correct: false },
      { id: 'd', text: 'Magnesium (Mg)', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_302',
    exam_id: 'exm_ss1_test1',
    type: 'short_answer',
    content: 'Define atomic number and mass number.',
    marks: 3,
    expected_answer:
      'Atomic number is the number of protons in the nucleus of an atom. Mass number is the total number of protons and neutrons in the nucleus of an atom.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_303',
    exam_id: 'exm_ss1_test1',
    type: 'mcq',
    content: 'Which subatomic particle has no charge?',
    marks: 1,
    expected_answer: 'Neutron',
    mcq_options: [
      { id: 'a', text: 'Proton', is_correct: false },
      { id: 'b', text: 'Electron', is_correct: false },
      { id: 'c', text: 'Neutron', is_correct: true },
      { id: 'd', text: 'Positron', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_304',
    exam_id: 'exm_ss1_test1',
    type: 'mcq',
    content: 'The maximum number of electrons that can occupy the second shell is',
    marks: 1,
    expected_answer: '8',
    mcq_options: [
      { id: 'a', text: '2', is_correct: false },
      { id: 'b', text: '8', is_correct: true },
      { id: 'c', text: '18', is_correct: false },
      { id: 'd', text: '32', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_305',
    exam_id: 'exm_ss1_test1',
    type: 'short_answer',
    content: 'State three differences between metals and non-metals.',
    marks: 3,
    expected_answer:
      'Any three of: (1) Metals are good conductors of heat and electricity; non-metals are usually poor conductors. (2) Metals are malleable and ductile; non-metals are brittle when solid. (3) Metals are usually shiny (lustrous); non-metals are dull. (4) Metals form basic oxides; non-metals form acidic oxides. (5) Metals tend to lose electrons (form cations); non-metals tend to gain electrons (form anions).',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },
  {
    id: 'q_306',
    exam_id: 'exm_ss1_test1',
    type: 'mcq',
    content: 'An ion is formed when an atom',
    marks: 1,
    expected_answer: 'gains or loses electrons',
    mcq_options: [
      { id: 'a', text: 'gains or loses neutrons', is_correct: false },
      { id: 'b', text: 'gains or loses protons', is_correct: false },
      { id: 'c', text: 'gains or loses electrons', is_correct: true },
      { id: 'd', text: 'shares electrons with another atom', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: null,
    saved_to_bank: false,
  },

  // ────────────────────────────────────────────────────────────────
  // Bank-only questions (not yet attached to any exam)
  // ────────────────────────────────────────────────────────────────
  {
    id: 'q_901',
    exam_id: null,
    type: 'long_answer',
    content:
      'Explain the term electronegativity. State how it varies across a period and down a group, giving reasons for the trend.',
    marks: 6,
    expected_answer:
      'Electronegativity is the tendency of an atom in a covalent bond to attract the shared pair of electrons towards itself. Across a period it increases because nuclear charge increases while the number of shells stays the same, so the attraction for bonding electrons increases. Down a group it decreases because the number of shells increases, so the bonding electrons are further from the nucleus and are also shielded by inner-shell electrons.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_902',
    exam_id: null,
    type: 'mcq',
    content: 'Which of the following is NOT a property of giant ionic structures?',
    marks: 2,
    expected_answer: 'They conduct electricity in the solid state.',
    mcq_options: [
      { id: 'a', text: 'They have high melting and boiling points.', is_correct: false },
      { id: 'b', text: 'They are usually soluble in water.', is_correct: false },
      { id: 'c', text: 'They conduct electricity in the solid state.', is_correct: true },
      { id: 'd', text: 'They conduct electricity when molten or in solution.', is_correct: false },
    ],
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_general_ss2',
    saved_to_bank: true,
  },
  {
    id: 'q_903',
    exam_id: null,
    type: 'short_answer',
    content:
      'A compound contains 40% carbon, 6.7% hydrogen and 53.3% oxygen by mass. Determine its empirical formula. (C = 12, H = 1, O = 16)',
    marks: 5,
    expected_answer:
      'Moles: C = 40/12 = 3.33; H = 6.7/1 = 6.7; O = 53.3/16 = 3.33. Divide by smallest (3.33): C = 1, H = 2, O = 1. Empirical formula: CH2O.',
    mcq_options: null,
    has_image: false,
    image_url: null,
    question_bank_id: 'qb_waec_chem',
    saved_to_bank: true,
  },
];
